### ISSUE TITLE
Error: Cannot find module 'camelCase' - Linux environment 

### ISSUE THREAD

**Issue by Mosharush** [linsk1998/rollup-plugin-font#1]
# Bug report
On the Linux system when import camelCase as "camelCase" it's wrong and got the error:
```
cross-env NODE_ENV=production rollup --config build/rollup.config.js
[!] Error: Cannot find module 'camelCase'
Require stack:
- /builds/1/frontend/xyz/node_modules/rollup-plugin-font/index.js
- /builds/1/frontend/xyz/packages/xyz-ui/build/rollup.config.js
- /builds/1/frontend/xyz/node_modules/rollup/dist/shared/loadConfigFile.js
- /builds/1/frontend/xyz/node_modules/rollup/dist/bin/rollup
```

## To Reproduce

Steps to reproduce:

Run rollup builds with `rollup-plugin-font` plugin on Linux machine.

## Expected behavior

No errors at all, build done successfully.

System information

    OS: alpine Linux on Docker.
    Version of rollup-plugin-font: 1.1.1
    Version of Node.js: 14.16.1

**Comment by Mosharush** [comment]
I solve it on PR:
https://github.com/linsk1998/rollup-plugin-font/pull/2

**Comment by linsk1998** [comment]
I will publish on weekend
